### ISSUE TITLE
SSL error accessing docker webui

### ISSUE THREAD

**Issue by aligeee** [arabcoders/ytptube#63]
Hi there,

First off, thanks for wrapping up this great docker image! Has been working great till the latest version.

When I try to access the webui on my local network (running on unraid) I get the following SSL error:

"SSL_ERROR_RX_RECORD_TOO_LONG"

Any ideas?

**Comment by arabcoders** [comment]
Hello,

I have never run into this error before, and from quick google search it seems this error is unique to firefox due to misconfigured ssl certificate they suggest doing forced reload. `Ctrl+Shift+r` or `Shift+reload button`. 

They offer more suggestions in https://support.mozilla.org/en-US/questions/1222739

**Comment by aligeee** [comment]
Hmm weird - it wasn't working in either firefox or edge earlier but all seems to be working now without having changed anything...

Will mark this as closed & thanks again for the awesome docker image!
